/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  RevertLab,
  RevertLabInterface,
} from "../../../learn-labs/02-revert-decode/RevertLab";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "OnlyEven",
    type: "error",
  },
  {
    inputs: [],
    name: "alwaysFails",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "mustBeEven",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506102af8061001f6000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063128e6c371461003b578063a40231c614610045575b600080fd5b610043610075565b005b61005f600480360381019061005a9190610145565b6100b0565b60405161006c9190610181565b60405180910390f35b6040517f08c379a00000000000000000000000000000000000000000000000000000000081526004016100a7906101f9565b60405180910390fd5b6000806002836100c09190610248565b1461010257816040517fb4b149150000000000000000000000000000000000000000000000000000000081526004016100f99190610181565b60405180910390fd5b819050919050565b600080fd5b6000819050919050565b6101228161010f565b811461012d57600080fd5b50565b60008135905061013f81610119565b92915050565b60006020828403121561015b5761015a61010a565b5b600061016984828501610130565b91505092915050565b61017b8161010f565b82525050565b60006020820190506101966000830184610172565b92915050565b600082825260208201905092915050565b7f5245564552545f524541534f4e5f53414d504c45000000000000000000000000600082015250565b60006101e360148361019c565b91506101ee826101ad565b602082019050919050565b60006020820190508181036000830152610212816101d6565b9050919050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601260045260246000fd5b60006102538261010f565b915061025e8361010f565b92508261026e5761026d610219565b5b82820690509291505056fea26469706673582212204c2c2feef52718b2717c19291b0e387eeb5d69d942672404d773ab2ea0cadef064736f6c63430008220033";

type RevertLabConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: RevertLabConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class RevertLab__factory extends ContractFactory {
  constructor(...args: RevertLabConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      RevertLab & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): RevertLab__factory {
    return super.connect(runner) as RevertLab__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): RevertLabInterface {
    return new Interface(_abi) as RevertLabInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): RevertLab {
    return new Contract(address, _abi, runner) as unknown as RevertLab;
  }
}
