/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  CounterV2,
  CounterV2Interface,
} from "../../../../learn-labs/06-upgradeable/UpgradeableLab.sol/CounterV2";

const _abi = [
  {
    inputs: [],
    name: "increment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "newValue",
        type: "uint256",
      },
    ],
    name: "setValue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "value",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "version",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506102128061001f6000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80633fa4f2451461005157806354fd4d501461006f578063552410771461008d578063d09de08a146100a9575b600080fd5b6100596100b3565b6040516100669190610100565b60405180910390f35b6100776100b9565b6040516100849190610100565b60405180910390f35b6100a760048036038101906100a2919061014c565b6100c2565b005b6100b16100cc565b005b60005481565b60006002905090565b8060008190555050565b60016000808282546100de91906101a8565b92505081905550565b6000819050919050565b6100fa816100e7565b82525050565b600060208201905061011560008301846100f1565b92915050565b600080fd5b610129816100e7565b811461013457600080fd5b50565b60008135905061014681610120565b92915050565b6000602082840312156101625761016161011b565b5b600061017084828501610137565b91505092915050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b60006101b3826100e7565b91506101be836100e7565b92508282019050808211156101d6576101d5610179565b5b9291505056fea26469706673582212207fbbe6c1eace058ab0e40ad7f0580dfd04d154c81a66b09f0d2fc0c62e6b1b1c64736f6c63430008220033";

type CounterV2ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CounterV2ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CounterV2__factory extends ContractFactory {
  constructor(...args: CounterV2ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      CounterV2 & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): CounterV2__factory {
    return super.connect(runner) as CounterV2__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CounterV2Interface {
    return new Interface(_abi) as CounterV2Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): CounterV2 {
    return new Contract(address, _abi, runner) as unknown as CounterV2;
  }
}
