/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVRFConsumerLike,
  IVRFConsumerLikeInterface,
} from "../../mock_vrf_coordinator.sol/IVRFConsumerLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "randomWords",
        type: "uint256[]",
      },
    ],
    name: "fulfillRandomWords",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVRFConsumerLike__factory {
  static readonly abi = _abi;
  static createInterface(): IVRFConsumerLikeInterface {
    return new Interface(_abi) as IVRFConsumerLikeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVRFConsumerLike {
    return new Contract(address, _abi, runner) as unknown as IVRFConsumerLike;
  }
}
