/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface RevertLabInterface extends Interface {
  getFunction(nameOrSignature: "alwaysFails" | "mustBeEven"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "alwaysFails",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mustBeEven",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "alwaysFails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mustBeEven", data: BytesLike): Result;
}

export interface RevertLab extends BaseContract {
  connect(runner?: ContractRunner | null): RevertLab;
  waitForDeployment(): Promise<this>;

  interface: RevertLabInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  alwaysFails: TypedContractMethod<[], [void], "view">;

  mustBeEven: TypedContractMethod<[value: BigNumberish], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "alwaysFails"
  ): TypedContractMethod<[], [void], "view">;
  getFunction(
    nameOrSignature: "mustBeEven"
  ): TypedContractMethod<[value: BigNumberish], [bigint], "view">;

  filters: {};
}
