/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVRFCoordinatorLike,
  IVRFCoordinatorLikeInterface,
} from "../../findme.sol/IVRFCoordinatorLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "keyHash",
        type: "bytes32",
      },
      {
        internalType: "uint64",
        name: "subId",
        type: "uint64",
      },
      {
        internalType: "uint16",
        name: "requestConfirmations",
        type: "uint16",
      },
      {
        internalType: "uint32",
        name: "callbackGasLimit",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "numWords",
        type: "uint32",
      },
    ],
    name: "requestRandomWords",
    outputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVRFCoordinatorLike__factory {
  static readonly abi = _abi;
  static createInterface(): IVRFCoordinatorLikeInterface {
    return new Interface(_abi) as IVRFCoordinatorLikeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVRFCoordinatorLike {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IVRFCoordinatorLike;
  }
}
