/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IVRFConsumerLike } from "./IVRFConsumerLike";
export type { MockVRFCoordinator } from "./MockVRFCoordinator";
