/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  IndexerSource,
  IndexerSourceInterface,
} from "../../../learn-labs/09-indexer/IndexerSource";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "NumberSet",
    type: "event",
  },
  {
    inputs: [],
    name: "nextId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "setNumber",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506101918061001f6000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80633fb5c1cb1461003b57806361b8ce8c14610057575b600080fd5b61005560048036038101906100509190610104565b610075565b005b61005f6100c3565b60405161006c9190610140565b60405180910390f35b6000547f9b99fe1e164b2f59c23e957801d298251d28b6c108a9e5348c4128956db0483b826040516100a79190610140565b60405180910390a2600080815480929190600101919050555050565b60005481565b600080fd5b6000819050919050565b6100e1816100ce565b81146100ec57600080fd5b50565b6000813590506100fe816100d8565b92915050565b60006020828403121561011a576101196100c9565b5b6000610128848285016100ef565b91505092915050565b61013a816100ce565b82525050565b60006020820190506101556000830184610131565b9291505056fea26469706673582212204d6ea78aafc9b6b39ed734a5379f10c2e3c9de436d3f772f3c3c3b8a2db1639f64736f6c63430008220033";

type IndexerSourceConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: IndexerSourceConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class IndexerSource__factory extends ContractFactory {
  constructor(...args: IndexerSourceConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      IndexerSource & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): IndexerSource__factory {
    return super.connect(runner) as IndexerSource__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): IndexerSourceInterface {
    return new Interface(_abi) as IndexerSourceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IndexerSource {
    return new Contract(address, _abi, runner) as unknown as IndexerSource;
  }
}
