/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface EventReplayLabInterface extends Interface {
  getFunction(nameOrSignature: "nextId" | "ping"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Ping"): EventFragment;

  encodeFunctionData(functionFragment: "nextId", values?: undefined): string;
  encodeFunctionData(functionFragment: "ping", values: [string]): string;

  decodeFunctionResult(functionFragment: "nextId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ping", data: BytesLike): Result;
}

export namespace PingEvent {
  export type InputTuple = [
    from: AddressLike,
    id: BigNumberish,
    message: string
  ];
  export type OutputTuple = [from: string, id: bigint, message: string];
  export interface OutputObject {
    from: string;
    id: bigint;
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EventReplayLab extends BaseContract {
  connect(runner?: ContractRunner | null): EventReplayLab;
  waitForDeployment(): Promise<this>;

  interface: EventReplayLabInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  nextId: TypedContractMethod<[], [bigint], "view">;

  ping: TypedContractMethod<[message: string], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "nextId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ping"
  ): TypedContractMethod<[message: string], [void], "nonpayable">;

  getEvent(
    key: "Ping"
  ): TypedContractEvent<
    PingEvent.InputTuple,
    PingEvent.OutputTuple,
    PingEvent.OutputObject
  >;

  filters: {
    "Ping(address,uint256,string)": TypedContractEvent<
      PingEvent.InputTuple,
      PingEvent.OutputTuple,
      PingEvent.OutputObject
    >;
    Ping: TypedContractEvent<
      PingEvent.InputTuple,
      PingEvent.OutputTuple,
      PingEvent.OutputObject
    >;
  };
}
