/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  EventReplayLab,
  EventReplayLabInterface,
} from "../../../learn-labs/03-event-replay/EventReplayLab";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "message",
        type: "string",
      },
    ],
    name: "Ping",
    type: "event",
  },
  {
    inputs: [],
    name: "nextId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "message",
        type: "string",
      },
    ],
    name: "ping",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b5061028b8061001f6000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80633adb191b1461003b57806361b8ce8c14610057575b600080fd5b61005560048036038101906100509190610152565b610075565b005b61005f6100dd565b60405161006c91906101b8565b60405180910390f35b6000543373ffffffffffffffffffffffffffffffffffffffff167f70b9fa9db7248779b82f3212f84983f03b8f0b0df01c3e83a8c642df6897002a84846040516100c0929190610231565b60405180910390a360008081548092919060010191905055505050565b60005481565b600080fd5b600080fd5b600080fd5b600080fd5b600080fd5b60008083601f840112610112576101116100ed565b5b8235905067ffffffffffffffff81111561012f5761012e6100f2565b5b60208301915083600182028301111561014b5761014a6100f7565b5b9250929050565b60008060208385031215610169576101686100e3565b5b600083013567ffffffffffffffff811115610187576101866100e8565b5b610193858286016100fc565b92509250509250929050565b6000819050919050565b6101b28161019f565b82525050565b60006020820190506101cd60008301846101a9565b92915050565b600082825260208201905092915050565b82818337600083830152505050565b6000601f19601f8301169050919050565b600061021083856101d3565b935061021d8385846101e4565b610226836101f3565b840190509392505050565b6000602082019050818103600083015261024c818486610204565b9050939250505056fea26469706673582212209380be3212a919cd1f0a54b9137fcf9346bccb5e5294fdcff37d38ee60b7dafb64736f6c63430008220033";

type EventReplayLabConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EventReplayLabConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class EventReplayLab__factory extends ContractFactory {
  constructor(...args: EventReplayLabConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      EventReplayLab & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): EventReplayLab__factory {
    return super.connect(runner) as EventReplayLab__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EventReplayLabInterface {
    return new Interface(_abi) as EventReplayLabInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): EventReplayLab {
    return new Contract(address, _abi, runner) as unknown as EventReplayLab;
  }
}
