/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type UserStruct = { userAddress: AddressLike; amount: BigNumberish };

export type UserStructOutput = [userAddress: string, amount: bigint] & {
  userAddress: string;
  amount: bigint;
};

export interface FindMeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "MAX_REFUND_BPS"
      | "MIN_FUND_WEI"
      | "VRF_NUM_WORDS"
      | "callbackGasLimit"
      | "coordinator"
      | "donatedAmountByUser"
      | "donatedUsers"
      | "findAll"
      | "fulfillRandomWords"
      | "fund"
      | "keyHash"
      | "owner"
      | "pendingDonationCount"
      | "pendingDonations"
      | "requestConfirmations"
      | "subscriptionId"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DonationProcessed" | "DonationRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_REFUND_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_FUND_WEI",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VRF_NUM_WORDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "callbackGasLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "coordinator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "donatedAmountByUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "donatedUsers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "findAll", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fulfillRandomWords",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "fund", values?: undefined): string;
  encodeFunctionData(functionFragment: "keyHash", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingDonationCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingDonations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestConfirmations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptionId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_REFUND_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_FUND_WEI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VRF_NUM_WORDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callbackGasLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "coordinator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "donatedAmountByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "donatedUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "findAll", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fulfillRandomWords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "keyHash", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingDonationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingDonations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestConfirmations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscriptionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace DonationProcessedEvent {
  export type InputTuple = [
    donor: AddressLike,
    requestId: BigNumberish,
    grossAmount: BigNumberish,
    refundAmount: BigNumberish,
    netAmount: BigNumberish,
    refundBps: BigNumberish
  ];
  export type OutputTuple = [
    donor: string,
    requestId: bigint,
    grossAmount: bigint,
    refundAmount: bigint,
    netAmount: bigint,
    refundBps: bigint
  ];
  export interface OutputObject {
    donor: string;
    requestId: bigint;
    grossAmount: bigint;
    refundAmount: bigint;
    netAmount: bigint;
    refundBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DonationRequestedEvent {
  export type InputTuple = [
    donor: AddressLike,
    requestId: BigNumberish,
    grossAmount: BigNumberish
  ];
  export type OutputTuple = [
    donor: string,
    requestId: bigint,
    grossAmount: bigint
  ];
  export interface OutputObject {
    donor: string;
    requestId: bigint;
    grossAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FindMe extends BaseContract {
  connect(runner?: ContractRunner | null): FindMe;
  waitForDeployment(): Promise<this>;

  interface: FindMeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  MAX_REFUND_BPS: TypedContractMethod<[], [bigint], "view">;

  MIN_FUND_WEI: TypedContractMethod<[], [bigint], "view">;

  VRF_NUM_WORDS: TypedContractMethod<[], [bigint], "view">;

  callbackGasLimit: TypedContractMethod<[], [bigint], "view">;

  coordinator: TypedContractMethod<[], [string], "view">;

  donatedAmountByUser: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  donatedUsers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  findAll: TypedContractMethod<[], [UserStructOutput[]], "view">;

  fulfillRandomWords: TypedContractMethod<
    [requestId: BigNumberish, randomWords: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  fund: TypedContractMethod<[], [void], "payable">;

  keyHash: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingDonationCount: TypedContractMethod<[], [bigint], "view">;

  pendingDonations: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean] & {
        donor: string;
        grossAmount: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  requestConfirmations: TypedContractMethod<[], [bigint], "view">;

  subscriptionId: TypedContractMethod<[], [bigint], "view">;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_REFUND_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_FUND_WEI"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VRF_NUM_WORDS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "callbackGasLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "coordinator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "donatedAmountByUser"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "donatedUsers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "findAll"
  ): TypedContractMethod<[], [UserStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "fulfillRandomWords"
  ): TypedContractMethod<
    [requestId: BigNumberish, randomWords: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fund"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "keyHash"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingDonationCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingDonations"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean] & {
        donor: string;
        grossAmount: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "requestConfirmations"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "subscriptionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "DonationProcessed"
  ): TypedContractEvent<
    DonationProcessedEvent.InputTuple,
    DonationProcessedEvent.OutputTuple,
    DonationProcessedEvent.OutputObject
  >;
  getEvent(
    key: "DonationRequested"
  ): TypedContractEvent<
    DonationRequestedEvent.InputTuple,
    DonationRequestedEvent.OutputTuple,
    DonationRequestedEvent.OutputObject
  >;

  filters: {
    "DonationProcessed(address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      DonationProcessedEvent.InputTuple,
      DonationProcessedEvent.OutputTuple,
      DonationProcessedEvent.OutputObject
    >;
    DonationProcessed: TypedContractEvent<
      DonationProcessedEvent.InputTuple,
      DonationProcessedEvent.OutputTuple,
      DonationProcessedEvent.OutputObject
    >;

    "DonationRequested(address,uint256,uint256)": TypedContractEvent<
      DonationRequestedEvent.InputTuple,
      DonationRequestedEvent.OutputTuple,
      DonationRequestedEvent.OutputObject
    >;
    DonationRequested: TypedContractEvent<
      DonationRequestedEvent.InputTuple,
      DonationRequestedEvent.OutputTuple,
      DonationRequestedEvent.OutputObject
    >;
  };
}
