/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVaultLike,
  IVaultLikeInterface,
} from "../../../../learn-labs/05-reentrancy/ReentrancyLab.sol/IVaultLike";

const _abi = [
  {
    inputs: [],
    name: "deposit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVaultLike__factory {
  static readonly abi = _abi;
  static createInterface(): IVaultLikeInterface {
    return new Interface(_abi) as IVaultLikeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IVaultLike {
    return new Contract(address, _abi, runner) as unknown as IVaultLike;
  }
}
