/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type UserStruct = { userAddress: AddressLike; amount: BigNumberish };

export type UserStructOutput = [userAddress: string, amount: bigint] & {
  userAddress: string;
  amount: bigint;
};

export interface FindMeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_FUND_WEI"
      | "donatedAmountByUser"
      | "donatedUsers"
      | "findAll"
      | "fund"
      | "owner"
      | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "MIN_FUND_WEI",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "donatedAmountByUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "donatedUsers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "findAll", values?: undefined): string;
  encodeFunctionData(functionFragment: "fund", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "MIN_FUND_WEI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "donatedAmountByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "donatedUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "findAll", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export interface FindMe extends BaseContract {
  connect(runner?: ContractRunner | null): FindMe;
  waitForDeployment(): Promise<this>;

  interface: FindMeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_FUND_WEI: TypedContractMethod<[], [bigint], "view">;

  donatedAmountByUser: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  donatedUsers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  findAll: TypedContractMethod<[], [UserStructOutput[]], "view">;

  fund: TypedContractMethod<[], [void], "payable">;

  owner: TypedContractMethod<[], [string], "view">;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_FUND_WEI"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "donatedAmountByUser"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "donatedUsers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "findAll"
  ): TypedContractMethod<[], [UserStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "fund"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  filters: {};
}
